# Generated by Django 5.1.5 on 2025-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_period', models.IntegerField()),
            ],
        ),
    ]
