# Generated by Django 5.1.5 on 2025-01-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('usermanagement', '0002_remove_user_is_admin_user_max_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentplan',
            name='penalty_daily_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repaymentplan',
            name='penalty_grace_period',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('state', models.IntegerField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emi_day', models.IntegerField(null=True)),
                ('repayment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.repaymentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.userpayment')),
            ],
        ),
    ]
