# Generated by Django 5.1.5 on 2025-01-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='max_credits',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
